### PR TITLE
Issue 75: Validate SWX advisory TAC token order

### LINKED ISSUE #75: Invalid SWX advisory token order is not reported as a conversion issue
For example:
```
SWX ADVISORY
STATUS:           TEST
DTG:              20200625/1605Z
FCST SWX +24 HR:  26/1700Z NO SWX EXP 
NR RPLC:          2020/28
SWX EFFECT:       GNSS MOD
OBS SWX:          25/1605Z HNH HSH E180 - W180
FCST SWX +6 HR:   25/2300Z NO SWX EXP
FCST SWX +12 HR:  26/0500Z NO SWX EXP
FCST SWX +18 HR:  26/1100Z NO SWX EXP
RMK:              TEST. TEST. TEST. THIS IS A TEST SPACE WEATHER ADVISORY. PLEASE
DISREGARD.
CORRECTION - ADVISORY NUMBER 27 SUPERSEDED
NXT ADVISORY:     NO FURTHER ADVISORIES
ADVISORY NR:      2020/29
SWXC:             SWPC=
```

### PR DESCRIPTION
**Pull request by kasarit**
Fixes #75.
This does not currently check the order of individual OBS/FCST phenomena lines.
Depends on https://github.com/fmidev/fmi-avi-messageconverter-tac/pull/87

### CODE REVIEW

**Comment by petringo** [comment]
Looks good. I came up with few ideas on how to improve this.

**Errors found**

This goes still without errors:

```
SWX ADVISORY
STATUS:           TEST
DTG:              20200625/1605Z
FCST SWX +24 HR:  26/1700Z NO SWX EXP 
NR RPLC:          2020/28
SWX EFFECT:       GNSS MOD
OBS SWX:          25/1605Z HNH HSH E180 - W180
FCST SWX +6 HR:   25/2300Z NO SWX EXP
FCST SWX +12 HR:  26/0500Z NO SWX EXP
FCST SWX +18 HR:  26/1100Z NO SWX EXP
RMK:              TEST. TEST. TEST. THIS IS A TEST SPACE WEATHER ADVISORY. PLEASE
DISREGARD.
CORRECTION - ADVISORY NUMBER 27 SUPERSEDED
NXT ADVISORY:     NO FURTHER ADVISORIES
ADVISORY NR:      2020/29
SWXC:             SWPC=
```

It looks, that forecasts are not checked to exist before `RMK` and `NXT ADVISORY`.


**Testing forecast order**

It might be a good idea to check that observation occurs before any forecasts.

Maybe order of forecast labels should be checked at syntax level? To do that, we need to specialize the regex in `SWXPhenomena` lexeme to grab the hour and store it in the lexeme. Then the parser could check that hour of previous forecast is less than hour of current and is a multiplier of `6` between 6-24.


**Enhancing tests**

I was also thinking would it be worth to write a test, where a message would be declared as list of lines, and then test that all any order of lines, except original, produces a conversion issue.


**Cleaning code**

Although it seems to be the convention, it looks error-prone to always have to list lexeme identities _not_ expected before token under inspection. How about this kind of approach:

Split `AbstractTACParser.checkBeforeAnyOf()` into:

```
protected static ConversionIssue checkBeforeAnyOf(final Lexeme lexeme, final LexemeIdentity... toMatch) {
    return lexeme == null || toMatch == null || toMatch.length == 0 ? null : checkBeforeAnyOf(lexeme, new HashSet<>(Arrays.asList(toMatch)));
}

protected static ConversionIssue checkBeforeAnyOf(final Lexeme lexeme, final Set<LexemeIdentity> toMatch) {
    ConversionIssue retval = null;
    if (lexeme != null && toMatch != null && !toMatch.isEmpty()) {
        Lexeme toCheck = lexeme;
        while (toCheck.hasPrevious()) {
            toCheck = toCheck.getPrevious();
            final LexemeIdentity identity = toCheck.getIdentity();
            if (toMatch.contains(identity)) {
                retval = new ConversionIssue(ConversionIssue.Type.SYNTAX, "Invalid token order: '" + lexeme + "' was found after one of type " + identity);
            }
        }
    }
    return retval;
}
```

Then, in `SWXTACParser` class level:

```
private static final Set<LexemeIdentity> SWX_LEXEME_IDENTITIES = Collections.unmodifiableSet(new HashSet<>(
        Arrays.asList(LexemeIdentity.ADVISORY_STATUS_LABEL, LexemeIdentity.ADVISORY_STATUS,
                LexemeIdentity.DTG_ISSUE_TIME_LABEL, LexemeIdentity.ISSUE_TIME, LexemeIdentity.SWX_CENTRE_LABEL, LexemeIdentity.SWX_CENTRE,
                LexemeIdentity.ADVISORY_NUMBER_LABEL, LexemeIdentity.ADVISORY_NUMBER, LexemeIdentity.REPLACE_ADVISORY_NUMBER_LABEL,
                LexemeIdentity.REPLACE_ADVISORY_NUMBER, LexemeIdentity.SWX_EFFECT_LABEL, LexemeIdentity.SWX_EFFECT, LexemeIdentity.ADVISORY_PHENOMENA_LABEL,
                LexemeIdentity.ADVISORY_PHENOMENA_TIME_GROUP, LexemeIdentity.REMARKS_START, LexemeIdentity.NEXT_ADVISORY_LABEL,
                LexemeIdentity.NEXT_ADVISORY)));
```

and in `convertMessage()` method:

```
final HashSet<LexemeIdentity> retainingLexemeIdentities = new HashSet<>(SWX_LEXEME_IDENTITIES);
retainingLexemeIdentities.remove(LexemeIdentity.ADVISORY_STATUS_LABEL);
// Handle ADVISORY_STATUS_LABEL:
final ConversionIssue issue = checkBeforeAnyOf(match, retainingLexemeIdentities);
// ...
retainingLexemeIdentities.remove(...);
// Handle next...
// ...
```

**Comment by kasarit** [comment]
> I was also thinking would it be worth to write a test, where a message would be declared as list of lines, and then test that all any order of lines, except original, produces a conversion issue.

Do you mean that we'd test every permutation of a list with ~13 elements? The performance of that test would be abysmal, no?

**Comment by petringo** [comment]
Well, maybe testing each line on once every position while keeping other lines in order would be effective, also by test coverage? That would make only ~13×13 < 200 iterations.

**Comment by kasarit** [comment]
Sounds reasonable :+1:

**Comment by kasarit** [comment]
What about cases where a line is interpreted as a continuation of a remark? It might be possible to prioritize the lexing of labels higher but I'm not sure if it's feasible. I tried to play around with the occurrence frequencies and that broke all sorts of things.

**Comment by petringo** [comment]
Basically, if a label is interpreted as part of remark content, we should normally end up in an error of missing label. There is an exception with conditional labels `STATUS:` and `NR RPLC:` which do not yield an error when missing. The correct way to handle this is not obvious, as the Annex 3 does not actually deny use of `STATUS:` and `NR RPLC:` within the remark, though it may be considered as bad practice.

The easiest way to handle this might be to check that `RMK:`, when found, exists _after_ a forecast label (`LexemeIdentity.ADVISORY_PHENOMENA_LABEL`) in the lexeme sequence. Then we should always get some error when `RMK:` is not located correctly.

What comes to testing, I proposed [earlier](https://github.com/fmidev/fmi-avi-messageconverter-tac/pull/89#issuecomment-734846346):

> Well, maybe testing each line on once every position while keeping other lines in order would be effective, also by test coverage? That would make only ~13×13 < 200 iterations.

I realized that this does not cover the case mentioned in the [review comment above](https://github.com/fmidev/fmi-avi-messageconverter-tac/pull/89#issuecomment-734296115).

P.S. Sorry, I accidentally had copied the [original](https://github.com/fmidev/fmi-avi-messageconverter-tac/issues/75#issue-728102215) example to the [review comment above](https://github.com/fmidev/fmi-avi-messageconverter-tac/pull/89#issuecomment-734296115). I changed the example now to the one I meant.

**Review by petringo — COMMENTED** [review]
Looks good. I would only suggest to consider some code cleaning in `SWXTACParser.java` for maintainability.

**Review by petringo — COMMENTED** [review]
Great, thanks!

**Pull request merged**
